name: Send Email

on:
    push:
        branches:
            - main

jobs:
    send_email:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: print hello
          run: echo "Hello world"

        - name: Send email
          uses: dawidd6/action-send-mail@v4
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: GitHub Actions Workflow Notification
            body: This is a test email sent from GitHub Actions.
            to: brk4193@gmail.com
            from: brkawsdev@gmail.com
